package Base;

import javax.swing.JFrame;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Vi-PC
 */
public class FormCadastros extends javax.swing.JFrame {

    double imc=0;
    /**
     * Creates new form FormCadastros
     */
    public FormCadastros() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        alturaValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pesoValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idadeValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        moderado = new javax.swing.JCheckBox();
        bemativo = new javax.swing.JCheckBox();
        ativo = new javax.swing.JCheckBox();
        sedentario = new javax.swing.JCheckBox();
        masculino = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        feminino2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Novo Cadastro Usúario");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Digite seu nome de Usúario :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Digite sua senha :");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cadastrar Usúario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Altura (m) :");

        alturaValor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Peso Atual (Kg) :");

        pesoValor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setText("Idade :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Nivel De Atividade Fisica :");

        moderado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        moderado.setText("Moderado");

        bemativo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bemativo.setText("Bem Ativo");

        ativo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ativo.setText("Ativo");
        ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoActionPerformed(evt);
            }
        });

        sedentario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sedentario.setText("Sedentario");
        sedentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedentarioActionPerformed(evt);
            }
        });

        masculino.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        masculino.setText("Masculino");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Sexo :");

        feminino2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        feminino2.setText("Feminino");
        feminino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feminino2ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconfinder_user_close_add_103747 (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(alturaValor)
                            .addComponent(pesoValor)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addComponent(feminino2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(masculino))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(sedentario)
                                            .addGap(18, 18, 18)
                                            .addComponent(moderado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ativo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bemativo))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel8)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idadeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idadeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sedentario)
                    .addComponent(moderado)
                    .addComponent(ativo)
                    .addComponent(bemativo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feminino2)
                            .addComponent(masculino)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alturaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double caloria = 0;
        
        double peso = Double.parseDouble(pesoValor.getText().replace(',', '.'));
        double altura = Double.parseDouble(alturaValor.getText().replace(',', '.'));
        double idade = Double.parseDouble(idadeValor.getText().replace(',', '.'));

        if (feminino2.isSelected()) {
            caloria = 65.5 + (9.6 * peso) + (1.8 * altura) - (4.7 * idade);
        } else if (masculino.isSelected()) {
            caloria = 66 + (13.7 * peso) + (5 * altura) - (6.5 * idade);
        }

        if (sedentario.isSelected()) {
            caloria = caloria * 1.2;
        } else if (moderado.isSelected()) {
            caloria = caloria * 1.3;
        } else if (ativo.isSelected()) {
            caloria = caloria * 1.5;
        } else if (bemativo.isSelected()) {
            caloria = caloria * 1.7;
        }

        imc = peso / (altura * altura);

        JOptionPane.showMessageDialog(null, "Operação realizada com sucesso");
        JOptionPane.showMessageDialog(null,
                String.format("Seu Gasto Calorico é: %.2f , por dia", caloria));

        if (imc < 18) {
            JOptionPane.showMessageDialog(null,
                    String.format("Seu IMC é: %.2f \n Classificação : Magreza ", imc));
        } else if (imc >= 18 && imc < 25) {
            JOptionPane.showMessageDialog(null,
                    String.format("Seu IMC é: %.2f \n Classificação : Adequado ", imc));
        } else if (imc >= 25 && imc < 30) {
            JOptionPane.showMessageDialog(null,
                    String.format("Seu IMC é: %.2f \n Classificação : Sobrepeso ", imc));
        } else if (imc >= 30 && imc < 35) {
            JOptionPane.showMessageDialog(null,
                    String.format("Seu IMC é: %.2f \n Classificação : Obesidade Grau 1 ", imc));
        } else if (imc >= 35 && imc < 40) {
            JOptionPane.showMessageDialog(null,
                    String.format("Seu IMC é: %.2f \n Classificação : Obesidade Grau 2 ", imc));
        }
        
        FormLogin.usuarioss.add(
                new usuarios(
                        jTextField1.getText(), jTextField2.getText(), imc, caloria
                ));
        
        //DESMARCAR todos os CheckBox
        for(Component comp : getContentPane().getComponents()){
            if (comp instanceof JCheckBox){
                JCheckBox chk = (JCheckBox)comp;
                chk.setSelected(false);
            }
        }
        
        bemativo.setSelected(true);
        masculino.setSelected(true);   
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativoActionPerformed

    private void sedentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedentarioActionPerformed

    private void feminino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feminino2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feminino2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaValor;
    private javax.swing.JCheckBox ativo;
    private javax.swing.JCheckBox bemativo;
    private javax.swing.JCheckBox feminino2;
    private javax.swing.JTextField idadeValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox masculino;
    private javax.swing.JCheckBox moderado;
    private javax.swing.JTextField pesoValor;
    private javax.swing.JCheckBox sedentario;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setTitle("Cadastrar Novo Usuario");
        this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(feminino2);
        bg.add(masculino);
        masculino.setSelected(true);
        ButtonGroup gb = new ButtonGroup();
        gb.add(sedentario);
        gb.add(moderado);
        gb.add(ativo);
        gb.add(bemativo);
        bemativo.setSelected(true);
    }
}
